'''''

== layout: docu

== SDKdemo

https://tech.swissmicros.com/SDKdemo/[https://tech.swissmicros.com/SDKdemo/]

=== This repo contains the sources for SDK demo project - simple scientific RPN calculator

* There is DMCP interface doc in progress see
http://technical.swissmicros.com/dmcp/doc/DMCP-ifc-html/[DMCP IFC doc]
(or you can download html zip from
http://technical.swissmicros.com/dmcp/doc/[doc directory]).

README file contains basic instructions how to prepare building
environment and build the program.

For the basic SDK with simple 'Hello World!' program look at DMCP_SDK
repository.

You can look at this SDKdemo project for more advanced project with
keyboard handling, more sophisticated LCD printing, power management,
build with Intel® Decimal Floating-Point Math Library, user defined
menus and more.

For ultimate project which uses other aspect of the DMCP system (like
system timers, bitmap printing to LCD or printing to IR printer) look at
sources of the DM42PGM project.

At this time the only source of information about the use of DMCP system
interface is based on the source code of DMCP programs.

[[the-sdk-and-related-material-is-released-as-nomas-not-manufacturer-supported]]
=== The SDK and related material is released as “NOMAS” (NOt MAnufacturer Supported).

. Info is released to assist customers using, exploring and extending
the product
. Do NOT contact the manufacturer with questions, seeking support, etc.
regarding NOMAS material as no support is implied or committed-to by the
Manufacturer
. The Manufacturer may reply and/or update materials if and when needed
solely at their discretion
